# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
    
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "465"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  
  spid_hostname: <%= ENV["SPID_HOSTNAME"] %>
  spid_metadata_path: <%= ENV["SPID_METADATA_PATH"] %>
  spid_login_path: <%= ENV["SPID_LOGIN_PATH"] %>
  spid_logout_path: <%= ENV["SPID_LOGOUT_PATH"] %>
  spid_acs_path: <%= ENV["SPID_ACS_PATH"] %>
  spid_slo_path: <%= ENV["SPID_SLO_PATH"] %>
  spid_default_relay_state_path: <%= ENV["SPID_DEFAULT_RELAY_STATE_PATH"] %>
  spid_digest_method: <%= ENV["SPID_DIGEST_METHOD"] %>
  spid_signature_method: <%= ENV["SPID_SIGNATURE_METHOD"] %>
  spid_acs_binding: <%= ENV["SPID_ACS_BINDING"] %>
  spid_slo_binding: <%= ENV["SPID_SLO_BINDING"] %>
  spid_organization_name: <%= ENV["SPID_ORGANIZATION_NAME"] %>
  spid_organization_display_name: <%= ENV["SPID_ORGANIZATION_DISPLAY_NAME"] %>
  spid_organization_url: <%= ENV["SPID_ORGANIZATION_URL"] %>
  
development:
  <<: *default
  secret_key_base: 9ced04fa4f6ad4efda2a8def548cc3f62273fe321df22c53affd115dcfea2a65861e1052861962c23e5c8d0f2870736faa9092a3bb8f8d622022486e70fade8b
  omniauth:
    developer:
      enabled: true
      icon: phone

test:
  <<: *default
  secret_key_base: a3f62a9636805e0376e921dea9cfb1a09480938023d250dfe02005978a6d63eb541cc6923a1ac0429180565ceec0da1f982877dfea7a32374789f19584df0ff2
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
 
  
  
  
