---
acs_list: 
  - 
    acs_url: https://partecipa.gov.it/spid/samlsso
    acs_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  - 
    acs_url: https://partecipa.formez.org/spid/samlsso
    acs_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  - 
    acs_url: https://www.ripam.cloud/api/spid/login
    acs_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  - 
    acs_url: http://test_spid_decidim/spid/samlsso
    acs_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
