---
slo_list: 
  - 
    slo_url: https://partecipa.gov.it/spid/samlslo
    slo_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
    response_location: https://partecipa.gov.it
  - 
    slo_url: https://partecipa.formez.org/spid/samlslo
    slo_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
    response_location: https://partecipa.formez.org
  - 
    slo_url: https://www.ripam.cloud/api/spid/logout
    slo_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  - 
    slo_url: http://test_spid_decidim/spid/samlslo
    slo_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
    response_location: http://test_spid_decidim